application: eternal-grove-130707
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:

# Twitter Bootstrap
- url: /bootstrap
  static_dir: bootstrap

- url: /stylesheets
  static_dir: stylesheets

- url: /js
  static_dir: js
  
- url: /images
  static_dir: images 
  
- url: /prefs
  script: prefs.application
  login: required
  
- url: /datapage
  script: prefs.application
  login: required
  


  
- url: /leaderboards
  script: main.application
  login: required

- url: /about
  script: main.application
  
- url: /leaderboards
  script: main.application
  login: required

>>>>>>> origin/master
- url: /home
  script: main.application

- url: /index
  script: main.application
  login: required

- url: /dqtoday
  script: main.application
  login: required

- url: /addtask
  script: main.application
  login: required
  
- url: .*
  script: main.application

libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"